name: ci

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: write  # allow commits from the workflow

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Schema validate benchmarks.json
        run: python scripts/validate.py

  render:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v4  # default: persist-credentials=true (uses GITHUB_TOKEN)

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Build list from data/benchmarks.json
        run: |
          python scripts/build_readme.py > _list.md
          wc -l _list.md || true
          head -n 5 _list.md || true

      - name: Inject list into README
        run: |
          python - <<'PY'
          import re, pathlib, sys
          rp = pathlib.Path("README.md")
          lp = pathlib.Path("_list.md")
          readme = rp.read_text(encoding="utf-8")
          new = lp.read_text(encoding="utf-8").strip()
          if "<!-- START:LIST -->" not in readme or "<!-- END:LIST -->" not in readme:
              print("Markers not found in README.md", file=sys.stderr)
              sys.exit(1)
          updated = re.sub(
              r"(<!-- START:LIST -->)(.*?)(<!-- END:LIST -->)",
              lambda m: m.group(1) + "\n" + new + "\n" + m.group(3),
              readme, flags=re.S,
          )
          rp.write_text(updated, encoding="utf-8")
          PY

      - name: Commit README (only if changed)
        run: |
          if git diff --quiet README.md; then
            echo "No changes to commit."
          else
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "chore: auto-render list from benchmarks.json"
            git push
          fi
