name: validate-and-render

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: write  # needed to commit README updates

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Schema validate benchmarks.json
        run: python scripts/validate.py

  render:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false  # git-auto-commit will use its own token

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Build list from data/benchmarks.json
        run: |
          python scripts/build_readme.py > _list.md
          cat _list.md

      - name: Inject list into README
        run: |
          python - <<'PY'
          import re, pathlib
          readme = pathlib.Path("README.md").read_text(encoding="utf-8")
          new = pathlib.Path("_list.md").read_text(encoding="utf-8").strip()
          updated = re.sub(
              r"(<!-- START:LIST -->)(.*?)(<!-- END:LIST -->)",
              r"\1\n" + new + r"\n\3",
              readme, flags=re.S,
          )
          pathlib.Path("README.md").write_text(updated, encoding="utf-8")
          PY

      - name: Commit changes (if any)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: auto-render list from benchmarks.json"
          file_pattern: README.md
